name: CI

on:
  push:
    branches:
      - "features*"
      - "feature/*"
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:post1234@localhost:5432/todo_api_db

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: post1234
          POSTGRES_DB: todo_api_db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npx prisma generate

      - run: npx prisma migrate deploy

      - run: npm run build

      - run: npm run test